### ISSUE TITLE
Add a space?

### ISSUE THREAD

**Issue by temp-999** [NMSCD/expedition-alphabet#2]
No hurry on this as I understand from cyberpunk2350 that you're busy. 

This may not catch on but a few enterprising people have started using the NMS alphabet to create messages of their own.  Naturally I thought of using the expedition-alphabet to decode them. 

https://forums.atlas-65.com/t/open-your-eyes/7651

Couple things came up:
 1) The character set doesn’t have a blank character representing a space so selecting your characters from your set results in run-on words in the output area.
 2) I have a 24" monitor. 2/3 of it is for my browser and 1/3 is for other. The character set by itself doesn’t completely fit into the 1/3 space let alone the addition of the input/output area.  Using the entire screen space and adjusting the window size still doesn't show everything in one window but I did get the complete character set which I ended up printing out.

**Comment by Khaoz-Topsy** [comment]
Ok I had a look at it and added the space character and made the options a bit more responsive. The changes are on version 0.1.22. You can see the version number at the bottom of the page 😋. 

Feel free to reopen this issue if the options still don't fit properly 😅
